#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a chromium desktop='^1'
bspc rule -a telegram-desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Autostart application
sxhkd &
picom --config /home/roy/.config/picom/picom.conf --backend glx &
#nitrogen --restore &
dunst &
bash ~/.config/polybar/launch.sh --colorblocks
#bash ~/.config/polybar/material/scripts/pywal.sh /home/roy/Pictures/wallpaper/car.jpg
#bash ~/.config/polybar/launch.sh --material

# touchpad
xinput set-prop "ELAN0420:00 04F3:3240 Touchpad" "libinput Tapping Enabled" 1

# scroll touchpad
xinput set-prop "ELAN0420:00 04F3:3240 Touchpad" "libinput Natural Scrolling Enabled" 1

# start mouse speed
xinput --set-prop "E-Signal USB Gaming Mouse" "libinput Accel Speed" -0.8

# default cursor
xsetroot -cursor_name left_ptr

# start wallpaper
feh --bg-fill /home/roy/Pictures/wallpaper/car.jpg

